version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11nm8yfjp2920"
s3_prefix = "hello-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
